---
- name: Install pip if not
  become: yes
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install Docker SDK for Python
  become: yes
  pip:
    name: docker
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes

- name: Pull the Nginx Docker image
  docker_image:
    name: nginx
    source: pull
    tag: "1.23.4"
  become: yes

- name: Run Nginx container
  docker_container:
    name: nginx
    image: "nginx:1.23.4"
    state: started
    ports:
      - "80:80"
  become: yes
